### ISSUE TITLE
feat: show h and 0 periods

### ISSUE THREAD

**Issue by nicholaschiang** [Orbiit/gunn-web-app#102]
You should add an option to show H and 0 Periods (just like you can turn SELF on and off).

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/64465332-f7ba7100-d0c0-11e9-82b0-1c202b2a73f3.png)
ok

**Comment by nicholaschiang** [comment]
I don't actually know. I used to have an H Period (before I got Ind Study) for AAR, but never had a 0 period. Just figured someone out there might want this but probably doesn't know about GitHub issues.

**Comment by SheepTester** [comment]
Yes, I will add eventually
