### ISSUE TITLE
expand thiqness of H period times

### ISSUE THREAD

**Issue by anematode** [Orbiit/gunn-web-app#104]
My jazz band class goes from 19:00 to 21:00 on Wednesdays, wholly outside of the current allowed range. I beseech you, please expand the range of H period to 22:00!!!

**Comment by SheepTester** [comment]
also a reminder to e x t e n d the slider

**Comment by SheepTester** [comment]
reminder for myself

**Comment by SheepTester** [comment]
like the sliders are TINY
![image](https://user-images.githubusercontent.com/22133785/64090019-d8f15e80-ccfd-11e9-96d3-70f3cf039773.png)
they could be e x t e n d
![dsfg](https://cdn.discordapp.com/attachments/500124272715366440/617935772443738132/unknown.png)
