### ISSUE TITLE
es malo

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#11]
quiero bueno por favor

**Comment by SheepTester** [comment]
Qué????

**Comment by PooleHenry** [comment]
Es mui mal! Tu es mal!

**Comment by SheepTester** [comment]
Qué quisiste dicer?

**Comment by Velosify** [comment]
eres mal eres mal eres mal!!!!!

**Comment by SheepTester** [comment]
Quién es mal?
Es Henry mal?
Es todo el mundo mal?

**Comment by PooleHenry** [comment]
SEAN ES ESTUPIDO y MUI MAL! GRANDE PROBLEMA!

**Comment by SheepTester** [comment]
Henry necesita aprender los acentos.

**Comment by Velosify** [comment]
Si todo mal

**Comment by PooleHenry** [comment]
Adios, amigos!

**Comment by PooleHenry** [comment]
Ahora estoy feliz, Grácias.
