### ISSUE TITLE
Advertisement Request

### ISSUE THREAD

**Issue by tinmarr** [Orbiit/gunn-web-app#112]
I just finished releasing a GPA Calculation Website. I was wondering if you could advertise it.
The URL is [gpac.tk](http://gpac.tk). 
The github is [github.com/tinmarr/GPA-Calculation-Website](https://www.github.com/tinmarr/GPA-Calculation-Website)

Thank you so much!!

**Comment by SheepTester** [comment]
I removed UGWA's PSA ability, and the new announcements system is intentionally not as easily seen, so how should I advertise this? Perhaps I could insert a text-based banner ad in the schedule or utilities section?

**Comment by tinmarr** [comment]
I like that idea. You could also a link or a button next to the calculator in the utilities section.
