### ISSUE TITLE
Advertisements

### ISSUE THREAD

**Issue by Objay1003** [Orbiit/gunn-web-app#113]
"Check out TAB's Haunted Escape Room this Friday!" 
"6-8 p.m in the Mitchell Park Community Center"
"Escape rooms and pumpkin painting"

**Comment by SheepTester** [comment]
Where should this ad be displayed?

/cc @anematode @Velosify

**Comment by Objay1003** [comment]
Maybe in the events section or announcements?

**Comment by Velosify** [comment]
Sounds like `Upcoming Events`/`Events` to me, but again, those aren't very visible (well I don't scroll all the way down there)

**Comment by anematode** [comment]
I don't think UGWA should have any ads

**Comment by SheepTester** [comment]
@anematode 
![image](https://user-images.githubusercontent.com/22133785/67168717-b83ba180-f35b-11e9-8fc6-81022cbfb80e.png)oof

**Comment by anematode** [comment]
scandalous

**Comment by SheepTester** [comment]
@Objay1003 Hardly anyone sees the announcements (though I have no analytics data to back this up)

**Comment by Velosify** [comment]
Personally, I also agree with @anematode
Ad ridden websites/software aren't very appealing to me

But ads should be added only if necessary

Or if people want it

**Comment by SheepTester** [comment]
Could rephrase the ad as "Check out Ronnie's XYZ" so it sounds more Gunn-related

**Comment by Velosify** [comment]
But where is it suitable to be placed

**Comment by Objay1003** [comment]
maybe top of schedule but probably smaller so its not too annoying. idk

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/67168825-a1497f00-f35c-11e9-8e6b-78dacc6a241d.png)
?

**Comment by Objay1003** [comment]
Sure
