### ISSUE TITLE
TAB's Holiday Night Advertisement

### ISSUE THREAD

**Issue by Objay1003** [Orbiit/gunn-web-app#115]
![image](https://user-images.githubusercontent.com/44220797/70174942-b1a68680-168a-11ea-8288-0302057d024d.png)

I just want to advertise the information on this poster.
Any form is fine

**Comment by SheepTester** [comment]
I will use the image, but just in case the user is offline and the image doesn't load, I will show a text version instead:

> TAB's Holiday Night
>
> Let's celebrate with a chocolate fountain, games, hot cocoa and gingerbread house decorating!
>
> December 6th, 6–8pm at Mitchell Park Teen Center
>
> Bring your student ID.
>
> —Palo Alto Teen Advisory Board

Or a one-line version:

> TAB's Holiday Night: Let's celebrate with a chocolate fountain, games, hot cocoa and gingerbread house decorating! December 6th, 6–8pm at Mitchell Park Teen Center. Bring your student ID. —Palo Alto Teen Advisory Board

(no Oxford comma in the image? oof lol)
