### ISSUE TITLE
display which days are "no school today" days in calendar

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#118]
would be interesting if the calendar was color coded or something to display which days students have school or not
hopefully it serves some purpose as well

All hail Gamepro5.

**Comment by Velosify** [comment]
this is apparently already in ugwisha but ugwa has a scrollable calendar which i believe is better

All hail Gamepro5.

**Comment by SheepTester** [comment]
oof Ugwisha had a scrolling calendar too but scrolling in JS is fussy
