### ISSUE TITLE
Dealing with time ranges

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#12]
On a normal Tuesday schedule, the schedule specifies that E period ends at 12:15 and lunch starts at 12:15.

It is 12:15; is it E period or lunch?

**Comment by Velosify** [comment]
Lunch? I guess
More important to know what starts than ends

**Comment by SheepTester** [comment]
In JLS, it'd be lunch; the bell starting ringing before the period ends

**Comment by PooleHenry** [comment]
It would be lunch because it's technically starting at when the bell rings,
right?

**Comment by SheepTester** [comment]
okay

they should've written [11:00, 12:15) for E period and [12:15, 12:55) for lunch

thanks for your responses, nonetheless
