### ISSUE TITLE
bro i have a question about the code overall

### ISSUE THREAD

**Issue by vivianth** [Orbiit/gunn-web-app#127]
what application do you use to edit the code? I prefer to use visual studio code for c++ but i'm not sure what to use for this project thing. Sublime text is not good for managing very large projects with multiple folders and such so I was wondering what you use?

**Comment by SheepTester** [comment]
I personally use Atom (or Vim for quick edits, Caret on a Chromebook, or Github's online file editor), but I'm pretty sure most editors should work. Although this project has many folders, I'm pretty sure Sublime Text should be able to handle it, as compared to other large projects this is fairly small

**Comment by SheepTester** [comment]
Closed for inactivity
