### ISSUE TITLE
Multiple barcodes

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#13]
Would it be helpful/useful to allow multiple barcodes? They could be labeled and/or colour coded (not on the barcode, of course); this could be useful for, for example, signing in multiple people for Flex

**Comment by Velosify** [comment]
Should it be saved to cache as the form of the id number entered?
How would it be selected and entered

**Comment by SheepTester** [comment]
@Velosify each barcode with its own input for the ID can have a remove button if there are >1, and there can be an add button to add more barcodes

To save, the ID's will just be concatenated together with `ids.join(',')` and separated when loading with `ids.split(',')`

**Comment by Velosify** [comment]
@SheepTester Do you press a button to save the ID? Also would a naming system for each id help
Then the removal of the IDs
I'm mainly talking about the interface

**Comment by SheepTester** [comment]
@Velosify oh yes, I should probably add a way to label the barcodes

The barcode [currently autosaves](https://orbiit.github.io/gunn-web-app/), and I don't plan on removing it

The UI might look like something like this:
![image](https://user-images.githubusercontent.com/22133785/30674583-0ff877c8-9e30-11e7-9e3c-276ef5110183.png) (names from a random name generator site *cough*) (btw that's from Skejl, a schedule app that was intended to also allow you to edit the schedule, but it didn't get very far and I didn't intend to add alternate schedule support)

**Comment by Velosify** [comment]
Nice design
However the background seems "milky" like in ios 8/9 (I forgot which one)

**Comment by SheepTester** [comment]
@Velosify it's the settings window, which is translucent white, and the content behind it is blurred

**Comment by Velosify** [comment]
@SheepTester I don't like the translucency
Looks too milky and ugly

**Comment by Velosify** [comment]
@SheepTester Actually its fine
Translucent enough for some of the background to be blurred while not being too distracting

**Comment by SheepTester** [comment]
Implemented
