### ISSUE TITLE
Option to add zoom links (similar to adding period names)

### ISSUE THREAD

**Issue by acrantel** [Orbiit/gunn-web-app#137]
It would be cool if we could just go to UGWA and be able to click on the zoom link for a class. 

Perhaps it could go in this section
![image](https://user-images.githubusercontent.com/40174697/90304914-300b2780-deac-11ea-96aa-47a65a33b6e7.png)

**Comment by acrantel** [comment]
The option to add a Zoom link, I mean

**Comment by SheepTester** [comment]
I am thinking that instead of doubling the height of the thing by adding a new row of inputs, I'll just add a link icon on the right that can be set to something that'll open xyz time units before a period starts
