### ISSUE TITLE
Add current seconds timer

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#14]
Sometimes when you watch in awe as the schedule updates, it's nice to know when the minute is about to change

**Comment by Velosify** [comment]
Me gusta la idea

**Comment by SheepTester** [comment]
@Velosify btw you can add reactions to issues

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/30677946-bfcb3a24-9e43-11e7-8f55-f473326420e9.png)
Implementing in next commit :)
