### ISSUE TITLE
Webpack + node modules + dynamic import code splitting

### ISSUE THREAD

**Issue by illemonati** [Orbiit/gunn-web-app#141]
I noticed that you guys mintified all your code during build but aren't doing much splitting.
Consider to switching to a webpack + node modules architecture for

1. Easier dependency management
2. Better mintification
3. Code splitting via dynamic imports (so users can only load what they need to use, if ur using service worker it should still load every thing if u set it up right) (Also this is not really a webpack only thing but just a thing in general that u should do, but webpack also support it so you can have dynamic import + code mintification + node_modules bundling)

**Comment by anematode** [comment]
No thanks! We like our code only partially minified. Full minification can introduce off-flavors into the app that are undesirable for high-quality codebases.

**Comment by SheepTester** [comment]
Adding on, UGWA doesn't use any dependencies for the front end, and Rollup (*not* Webpack) is already used to bundle UGWA. Dynamic ES module imports are already used for loading non-English languages, dynamic script tag loading is used for loading the Google Maps, and everything else is pretty much used on load, so no code splitting is needed.

**Comment by illemonati** [comment]
Cool.
I just saw there was a library section in the readme. I didn't actually read the code. You guys seem to have all the "libraries" as single js files. 
It might be helpful for others wanting to use your libraries or if you ever consider to use them in the future to make them into a module to publish on npm or somewhere.

**Comment by illemonati** [comment]
Also @anematode , Can you elaborate what you mean by 
> Full minification can introduce off-flavors into the app that are undesirable for high-quality codebases.
I'm genuinely interested in the topic because I always assumed that "codebase" means the code that you are writing, and using, rather than the final deployed version the user sees. 
If minified code is generated at build/compile time whatever u want to call it before you push it to pages, how would it affect the "codebase", the code that you are writing?

**Comment by SheepTester** [comment]
> I just saw there was a library section in the readme. I didn't actually read the code. You guys seem to have all the "libraries" as single js files.
> It might be helpful for others wanting to use your libraries or if you ever consider to use them in the future to make them into a module to publish on npm or somewhere.

Well, such are JavaScript modules. You could use Deno, but you'd need to specify the export types if you used TS. There's also [awesome-new-gunn-schedule-package](https://www.npmjs.com/package/awesome-new-gunn-schedule-package) on NPM

**Comment by anematode** [comment]
Webpack is a terrifying technique. In our experience with Webpack, the code is so grotesquely compressed that it starts to ooze pus and leachate. See the output of https://anematode.github.io/velar/build/. Only God knows what the code even says at this point. Imagine if a user reported an error at line 1, position 28150. I would lose my shit

**Comment by illemonati** [comment]
@anematode It seems that you already have source map enabled for velar. 

The errors should be reported by the source map in browsers. So it doesn't seem like that would be a problem.

<img width="1792" alt="Screen Shot 2020-08-23 at 1 58 49 PM" src="https://user-images.githubusercontent.com/40131775/90988615-05bf0700-e549-11ea-82c1-e6682e4ee2f6.png">
