### ISSUE TITLE
[Proposal] Generic School Web app

### ISSUE THREAD

**Issue by illemonati** [Orbiit/gunn-web-app#142]
It seems all of the features I've seen in the gunn web app doesn't have anything to do specifically for gunn. 
It might be great to open up the webapp to make it simple for other schools to use it.

The bell schedule, clubs, staff list, map, can be configured with a standardized configuration file, listing out the schedule, clubs, staff, and picture of map.

The settings, gpa, bar code, student resources seem to be fine without any changes (besides having the class settings be diffrent based on the generic bell schedule config file)

I know that the gunn web app is pretty complete for the most part (at least it feels that way to me, has everything I would want), so the next step might be to set up a version of it that takes in configuration files for schedule, clubs, staff list, map, school name&logo, and just any school-specific stuff, and allow every school to use the cool ui you've built.

**Comment by illemonati** [comment]
Also maybe write a tutorial to set up you're own <school name> web app by providing the right configs and running a command.

**Comment by SheepTester** [comment]
Out of scope for UGWA. [Ugwisha](https://github.com/Orbiit/ugwisha) does have better configuration support for other schools (having once had a Paly version), but it lacks documentation
