### ISSUE TITLE
Time Zones

### ISSUE THREAD

**Issue by illemonati** [Orbiit/gunn-web-app#148]
It would be great if UGWA can support being in different timezone. 
Normally this wouldn't be too necessary but since its zoom school people could be in different timezone. 

## this is not a hypothetical situation

I am in Florida right now and ugwa isn't working for me as using my current system time (GMT-4) and applying to the schedule times in (GMT-7). So everything is completely screwy.

Can you either add an ability to set time zone or detect my timezone and apply it to the schedule properly. 
This would be really useful as I've come to be quite dependent on ugwa lately and it's a shame to not be able to use it.

**Comment by SheepTester** [comment]
time zones are hard but maybe

**Comment by illemonati** [comment]
If anyone else is currently having this problem while lord and master Sean work on a fix.
You can use my quick 5 lines of code monkey patched version for now.
https://illemonati.gitlab.io/gunn-web-app/
