### ISSUE TITLE
Settings and About

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#15]
I'm working on the app design right now ([demo here](https://orbiit.github.io/gunn-web-app/appdesign.html))

I plan to **only have** a **bottom navigation** (which currently mostly follows the material design guidelines, except for the shadow, and possibly the ripple animation but the guidelines aren't very clear on those). However, Material Design says that there should only be a max of 5 items, and we've hit that max. (also, the items fit just perfectly on phones)

So **how should we incorporate the settings** and about pages? Should we **have a FAB** (floating action button), **merge a section** with another and replace it with settings, or **hide the button in one of the sections**? Or should there be a **touch gesture/keyboard shortcut** that opens it?

The settings section will include an option to **toggle dark/light themes**, **change the colours/labels** of the periods, and whatever else you want to include

Sorry for the long post, I decided to bold random parts to break it up.

(who here agrees that the material ripple effect is the best thing Google has ever made?)

**Comment by Velosify** [comment]
Maybe something like your sheep icon on sheeptester?

(yes ripple effect is the best)

**Comment by SheepTester** [comment]
@Velosify The sheep icon does not follow the material design guidelines

**Comment by SheepTester** [comment]
I've replaced the `barcode` section with `options`; I suppose I'll put the barcode generator at the top of the options page

**Comment by Velosify** [comment]
How about moving maps and barcodes together as utilities?

**Comment by SheepTester** [comment]
Sure

We can use [build](https://material.io/icons/#ic_build) perhaps for the icon

**Comment by Velosify** [comment]
Ok

**Comment by SheepTester** [comment]
kay I think everything is fine now
