### ISSUE TITLE
Barcode View Button functioning oddly on iOS 12.3.1 Safari

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#150]
![1F790DCB-0E6D-4343-80E3-F13558F6B992](https://user-images.githubusercontent.com/29491154/93797097-a3f9c780-fbf0-11ea-8571-2ffd988c14c9.jpeg)
This button does not always bring up the full screen barcode view on my device.

iPhone 7, iOS 12.3.1
iOS Safari version 12.1

Upon opening UGWA in portrait mode, the  button does the animation but does not bring up the barcode. From there, if I go to landscape mode, the button functions again, bringing up the barcode. After this, if I go back to portrait mode the button will function again until the page is zoomed in or I click on another tab.

I will try to film this behavior later to demonstrate exactly what I mean.

**Comment by SheepTester** [comment]
Hmm, it seems to work on my Dad's iPhone, but he's on iOS 14. Are there any errors in the error log? Maybe the thing that closes the barcode is also detecting the click to show the barcode

**Comment by PooleHenry** [comment]
Hmm, it seems like that might be the case - I noticed that if I scroll down a minuscule amount the button will work. Anyway, I will probably update my iOS sometime, which I suspect most users already have.
