### ISSUE TITLE
New logo for UGWA

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#156]
The current G is kind of ew, and Ugwisha's is way better but it's a shame to see it go to waste. Check with Brandon before implementing though

Idea (to distinguish from Ugwisha):
![image](https://user-images.githubusercontent.com/22133785/94626835-c46cf600-0270-11eb-8aea-e83876294a5d.png)

**Comment by PooleHenry** [comment]
Lol speedometer
