### ISSUE TITLE
Add world domination

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#157]
It is good.

**Comment by SheepTester** [comment]
Out of scope

**Comment by nicholaschiang** [comment]
Bruh, this just showed up on my GitHub notifications... I don't think you know how to use GitHub Issues haha. 😛

**Comment by nicholaschiang** [comment]
Bruh @SheepTester, this just showed up on my GitHub notifications... I don't think you know how to use GitHub Issues haha. 😛
