### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#17]
responsive design or something please
ripple effect hangs too long on smaller devices
still I like the design :D

**Comment by SheepTester** [comment]
I'll make the speed dependent on how long it has to travel instead of a constant 500ms

**Comment by Velosify** [comment]
Anyway to detect and use screen size?

**Comment by SheepTester** [comment]
Yes, but I'm using the button size instead

**Comment by Velosify** [comment]
I see

**Comment by SheepTester** [comment]
Fixed
