### ISSUE TITLE
More Customization

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#19]
Is it possible to change the colors for flex/lunch/brunch in addition to the original ones
sometimes it won't blend well with colors

**Comment by SheepTester** [comment]
And maybe also labels; it'd be nice to be able to change lunch to "munch much time"

**Comment by Velosify** [comment]
Lol yes I agree

**Comment by SheepTester** [comment]
Implemented in next commit :)

![image](https://user-images.githubusercontent.com/22133785/30677894-6e4cca96-9e43-11e7-9aed-d60cd1911aea.png)

**Comment by SheepTester** [comment]
Btw, this required having to add support for making saves convert to new save formats
