### ISSUE TITLE
Non deterministic sheep images

### ISSUE THREAD

**Issue by ky28059** [Orbiit/gunn-web-app#194]
From https://discord.com/channels/710932856251351111/710936824121655396/823014849831108640

> it seems that https://orbiit.github.io/gunn-web-app/?date=2021-3-20 produces non deterministic sheep image output
> to my knowledge this doesn't happen on :eyes: , despite using the same seeding function
> maybe its the leftover milliseconds?

**Comment by SheepTester** [comment]
The new `Day` system fixes this but it's not released yet oops
