### ISSUE TITLE
System theme preference as default

### ISSUE THREAD

**Issue by illemonati** [Orbiit/gunn-web-app#195]
can u guys make the default light/dark theme based on the system theme via prefers-color-scheme rather than light theme as default.

i need non broken eyes without switching
thx

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/112534197-04b4b900-8d68-11eb-9380-ca012a3c3cf7.png)
You can change the theme in settings

**Comment by illemonati** [comment]
When people first discover this app or if they just switch devices they can have the theme match their system theme so everything looks aligned by default, without needed to dig into settings. 

For my specific use case i don't save any data in between browser sessions so I have to switch it every time I restart my browser.
It's a bit annoying to have to switch every time. 

But I do have it configured where prefers-color-scheme will detect i prefer dark mode,
which would remove this issue.
