### ISSUE TITLE
game

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#21]
Perhaps we should add a small **simple** game, like the Chrome dinosaur game

It can be anything, like a dodge/catch game, or a game with randomly generated levels. It can't have a point where one can consider themselves "finished" with the game (eg a storyline or "levels" or anything that is unlocked through playing), be multiplayer, or require sounds

Examples (we can make a clone of one of these games, but people'll accuse us of doing that):
- Chrome dino game
- flappy bird
- 2048
- one of those jumpy-platform games
- one of those stacking games

We also might want to make the games touch-friendly, so minimal controls and typing would be best

**Comment by SheepTester** [comment]
Tagging @Velosify and @PooleHenry for discussion and ideas

Perhaps we can make this an easter egg and hide the game in a fake staff's contact info in the staff list?

**Comment by Velosify** [comment]
Maybe into the easter bunny character?
The Toast Robot wants a dodge game

**Comment by SheepTester** [comment]
I've made at least two dodge games on Scratch: [Dodge](https://scratch.mit.edu/projects/52801854/) and [Speed Dodge](https://scratch.mit.edu/projects/72775148/)

**Comment by Velosify** [comment]
I think I prefer Speed Dodge since it's simpler and might be easier to create

**Comment by SheepTester** [comment]
I need someone to draw the enemies and the player and the background

**Comment by PooleHenry** [comment]
I think I can try that. What should the dimensions be?

**Comment by SheepTester** [comment]
It doesn't really matter; it can always be rescaled

**Comment by Velosify** [comment]
@SheepTester What's the concept or main idea
Is it just a box?
aka what are the details

**Comment by SheepTester** [comment]
Just make it like Speed Dodge, I guess

**Comment by Velosify** [comment]
Why not just take the costumes of it then?

**Comment by SheepTester** [comment]
@Velosify oh oh yeah oops

**Comment by SheepTester** [comment]
Okay, we're making [the Unoriginal Game](https://orbiit.github.io/gunn-web-app/games/connect4.html)! 🎉

**Comment by SheepTester** [comment]
Snake game was added in f1d83c60ea8e324fb25f12302f371df9f808b1c9, which should suffice.
