### ISSUE TITLE
Other languages support

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#25]
It'd be cool to have the app available in multiple languages

The current app was not designed with this in mind, so implementation of this would be messy, so this'll probably be placed in UGWA 2

However, Gunn themselves do not provide information such as events, alternate schedules, or staff information in other languages. Either we leave them in English, leave everything in English and reject this suggestion, or find a way to convert the alternate schedules and staff info into other languages

Also, I have very little knowledge in RTL languages and designing websites/apps accommodating them. Languages like German with longer words might make some labels not fit correctly on phones, while languages like Chinese with very short words might leave awkward whitespace behind

**Comment by PooleHenry** [comment]
You might want to look at the Google Translate plugin made by Google [here](https://translate.google.com/manager/website/add). It seems like it just looks for text fields and runs them through google translate, so it probably won't break styling. However, it looks like it hasn't been updated to Material Design (it's got the old Google 'g' and skeuomorphic styling), so it might look weird with the aesthetic of the app.

**Comment by SheepTester** [comment]
Support for languages was added in 3b015dc3688cde55cab298061a0986c0367ffb16 and [following commits](https://github.com/Orbiit/gunn-web-app/commits/master?after=133c9c094368051ec6988fe0c370d1447fff4e84+0)
