### ISSUE TITLE
Staff List Bug?

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#27]
The human named Robert Ceja seems to be in the `null` department or something
![screen shot 2017-10-01 at 11 39 54 am](https://user-images.githubusercontent.com/22160233/31057796-42b1db76-a69d-11e7-8b89-b8e527af69c5.png)
Also each staff member starts with the word `title` before their occupation or whatever it's called
![screen shot 2017-10-01 at 11 39 29 am](https://user-images.githubusercontent.com/22160233/31057803-55d50908-a69d-11e7-8349-6e853755df4a.png)

**Comment by Velosify** [comment]
Perhaps there should be semicolons between the indicator and the information when clicked on a member
![screen shot 2017-10-01 at 11 38 44 am](https://user-images.githubusercontent.com/22160233/31057785-1c4cad08-a69d-11e7-8bf1-9c3ce1d54a73.png)

**Comment by SheepTester** [comment]
`:` is a colon; `;` is a semicolon.

I suppose since bolded Roboto doesn't show up well on Apple computers I'll have to add the colons

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/31063234-0fc0e7f4-a6e6-11e7-95d8-ad6ac040f898.png)
![image](https://user-images.githubusercontent.com/22133785/31063237-142a3e6c-a6e6-11e7-87f3-bd1c74e06278.png)
