### ISSUE TITLE
so we need a feature set

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#3]
we should create some sort of dynamic webpage template that works well with phones

plus we should have some features -- it probably should have

- [x] a basic schedule
- [x] alternate schedule finder (possibly use a scraper to rip them from [here](http://www.gisar.me/thegunnapp/list) or the official site)
- [x] a campus map (preferably with classrooms)
- [x] a staff list with contact info
- [x] upcoming activities (possibly rip them from the events calendar on the site)
- [x] flextime barcode generator (code 39)

let me know what else I need to add to this

**Comment by SheepTester** [comment]
Staff list available [here](http://gunn.pausd.org/people) on the Gunn website.

I've got the basic schedule [covered](https://orbiit.github.io/gunn-web-app/schedule/), so I'll check that one off, I suppose?

I mean it's a bit glitchy, but it'll do

I'm planning to add the pattern breakers (alternate schedules) soon

**Comment by SheepTester** [comment]
Barcode generator is done, and it's probably the easiest one to move around

**Comment by Velosify** [comment]
Shouldn't the barcode generator be more compact/

**Comment by PooleHenry** [comment]
@Velosify 

I think its fine, because with code 39, as long as you scale the bar length and spacing proportionally, the code could be 1 foot long, or one inch long, and still be picked up by a scanner.

**Comment by SheepTester** [comment]
@Velosify @PooleHenry Wikipedia specifies that the wide spaces/bars have to be anywhere from 2 to 3 times fatter than their narrower counterparts

I chose the 1:3 ratio because it reminds me of morse code

**Comment by SheepTester** [comment]
`staff.json` has been made, so all we have to do is use AJAX to grab that file and display it using some DOM trickery.

I'm planning to make a searching system similar to that of [eyo-dictionary](https://sheeptester.github.io/eyo-dictionary/), and display staff information like how Gunn currently does it

Is that okay?

**Comment by SheepTester** [comment]
[Here's the barcode font](https://fonts.google.com/specimen/Libre+Barcode+39+Text)

**Comment by SheepTester** [comment]
[Putting the stuff together](https://orbiit.github.io/gunn-web-app/appdesign.html)

**Comment by SheepTester** [comment]
```javascript
var r={};
jQuery('.views-table.cols-6 tbody tr').each(function(){
  var c=jQuery(this).children();
  r[c.eq(0).find('a').html().trim()]={
    "jobTitle":c.eq(1).html().trim(),
    "department":c.eq(2).find('a').html()?c.eq(2).find('a').html().trim():null,
    "phone":c.eq(3).html().trim(),
    "email":c.eq(4).html().trim(),
    "webpage":c.eq(5).find('a').length?c.eq(5).find('a').attr('href'):null}
});
JSON.stringify(r);
```
the Gunn website uses jQuery, so I was able to turn the staff list into a more readable JSON format :D

Also, apparently Stf. Ceja doesn't have a department

**Comment by SheepTester** [comment]
🎆 Only the map left! :D

**Comment by SheepTester** [comment]
original list all done! :D
