### ISSUE TITLE
Final testing and release of UGWA 1

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#30]
Hooray; UGWA 1 is almost ready to be out in the wild! 🎉

Just a few thing to be done:

## Testing
We need to ensure UGWA works in the following places:

- [x] Chromebook
- [x] Chrome on Windows
- [x] Chrome on Mac
- [ ] Chrome on Android
- [x] Safari on iOS
- (optional) Chrome on Linux

If possible, it'd be nice to know the oldest version UGWA 1 works on, but if it works on whatever version you have available, then that's fine by me.

We'll need to test:

- [the cache](https://orbiit.github.io/gunn-web-app/cachetest/) (open the page, then turn off the internet and reload)
- barcode generator (adding, editing, viewing, removing)
- the map image (panning, rotating, zooming)
- Google Maps
- club list (searching, scrolling, opening the full description)
- seconds timer
- date selector (events and schedule update accordingly, going more yesterday/tomorrow-wise)
- schedule (uses custom colours and names, alternate schedules show up properly)
- events
- staff list (searching, scrolling, opening the full description)
- settings (theme, period colours and names)

## Releasing
After the app seems to work properly

- [x] [write an about and credits section](https://github.com/Orbiit/gunn-web-app/blob/master/about.md)
- [x] combine all the JS files into one and minify it (should reduce loading time and storage required for cache)
- [x] do the same with CSS
- [x] add cache
- [x] move to `index.html`

After that, we can maybe work on a video that shows off what the app can do

**Comment by Velosify** [comment]
What about the desktop versions of Safari and Firefox

**Comment by Velosify** [comment]
Firefox seems to work fine but can be a little laggy
And the buttons are default
Of course I'm using an outdated version of it anyway

**Comment by Velosify** [comment]
@SheepTester Also who is going to test chrome on linux?

**Comment by SheepTester** [comment]
@Velosify Nobody

**Comment by SheepTester** [comment]
okay I hope it works on Android because I'm closing this now
