### ISSUE TITLE
Feature Requests (from people w/o Github account)

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#31]
Continuation of #5 for UGWA 2

**Comment by SheepTester** [comment]
> show relative date; if the selected date is today, show "today"; if it's tomorrow, show "tomorrow"

says TS

**Comment by SheepTester** [comment]
> show current hour and minute, not just seconds

**Comment by SheepTester** [comment]
> add Aaryan Agrawal as "supreme leader of the galaxy"

says AA

**Comment by SheepTester** [comment]
> on your gunn web app you should make it so it shows when the next break is
> one of my classmates just suggested that

says Gamepro5

**Comment by SheepTester** [comment]
> a button to return to today would be nice but not nessesary.

says acd

**Comment by SheepTester** [comment]
> Btw it would be helpful for UGWA to have a calculated class length next to each time: ex. A Period, 8:25 - 9:45, 1:20 Hours long
> Also of course make the homework planner too
> That's all the advice I currently have for it

says TS

**Comment by illemonati** [comment]
Can you wrap this in [cordova](https://cordova.apache.org/) and put it on play store and app store?

**Comment by SheepTester** [comment]
> when you scrape data that mentions SELF
> should flag it
> so you can manually replace it with something passive agressive

replace mentions of SELF with something else (should be optional?)

**Comment by SheepTester** [comment]
Future feature requests shall be made in a separate issue
