### ISSUE TITLE
Schedule issue?

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#32]
In the schedule section of the [UGWA](https://orbiit.github.io/gunn-web-app/appdesign.html) on the week of January 1-6 it says that there's school on Monday, but not the other weekdays. It also says winter break on Saturday, which also is not supposed to show
Did the schedule shift?

**Comment by SheepTester** [comment]
Yep, apparently the alternate schedules for Jan. 1-5 were shifted a day more tomorrow-wise
