### ISSUE TITLE
Schedule Issue?

### ISSUE THREAD

**Issue by Velosify** [Orbiit/gunn-web-app#34]
December 18's events says that there is an alternate schedule but the schedule denies it

**Comment by SheepTester** [comment]
The alternate schedules aren't grabbed from the events, they were grabbed from a PDF that I had to tediously convert into a more readable format.

UGWA II will grab the alternate schedules from the events like how the Gunn App already does it

**Comment by SheepTester** [comment]
I've manually fixed it
