### ISSUE TITLE
Request: ability to 'pin' notes to certain periods through browser cookies

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#35]
Say I would like to remember to turn in an assignment during a certain period. I could 'pin' a note to that period, the note would be saved in my cookies, and when I reload the page in the same client, the note would still be there.

Could this work? (I don't know much about cookies)

**Comment by SheepTester** [comment]
Acknowledged

**Comment by SheepTester** [comment]
So there's going to be a "note" which is like a description for each period where one can put the room number and whatnot.

There's also going to be a to-do list which is per-period, per-day, and will show up in Ugwa 2's fullscreen view as well.

By the way, one can react 👍 or 👎 on issue comments as well

**Comment by SheepTester** [comment]
@PooleHenry I've made a concept design [here](https://orbiit.github.io/gunn-web-app/designs/todo.html). Is that what you wanted? Is there anything I should change? etc

**Comment by Velosify** [comment]
Perhaps it should be collapsible?

**Comment by SheepTester** [comment]
@Velosify [It is.](https://orbiit.github.io/gunn-web-app/designs/dayview.html) (it'll go under the four lines)

**Comment by SheepTester** [comment]
Assignments were added in 964fc3e2810c3c9070f3d70c856a6466d286c93d, which basically function as described here
