### ISSUE TITLE
Small Feature Not Implemented

### ISSUE THREAD

**Issue by CannotHack** [Orbiit/gunn-web-app#37]
About a month ago, I asked to be named as the "Supreme Leader of the Universe" in the Staff section. 

Why has this not been implemented? Are you mortals trying to go against your leader?

**Comment by SheepTester** [comment]
It has been added to the checklist for Ugwa 2, so thus it has been implemented, at least in the _concept_ of Ugwa 2.

**Comment by CannotHack** [comment]
Great

**Comment by SheepTester** [comment]
implemented temporarily in a PSA

**Comment by SheepTester** [comment]
[at]13Ducks where did you go
