### ISSUE TITLE
alternate schedule for week of 2018-04-09

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#38]
## tuesday
> _Tuesday,April 10_
> 
> Period D (8:25-9:45)
> 
> Brunch (9:45-10:00)
> 
> Period E (10:00-11:15)
> 
> Period B (11:25-12:25)
> 
> Lunch (12:25-1:05)
> 
> Period A (1:05-2:05)
> 
> Period G (2:15-3:30)

## wednesday
> _Wednesday,April 11_
> 
> Period C (8:25-9:30)
> 
> Brunch (9:30-9:45)
> 
> ·       _**FRESHMEN**: to Assembly(9:45-10:45), to SELF (10:55-11:55), to FlexTime (12:05-1:05)_
> 
> ·       _**SOPHOMORES**: to FlexTime(9:45-10:45), to Assembly (10:55-11:55), to FlexTime (12:05-1:05)_
> 
> ·       _**JUNIORS**: to FlexTime(9:45-10:45), to FlexTime (10:55-11:55), to Assembly (12:05-1:05)_
> 
> ·       _**SENIORS**: to CASTstate test (9:45-11:55), to Assembly (12:05-1:05)_
> 
> Lunch (1:05-1:45)
> 
> Period F (1:45-2:45)
> 
> Staff Meeting (3:00-3:45)

## thursday
> _Thursday,April 12_
> 
> Period D (8:25-9:30)
> 
> Brunch (9:30-9:45)
> 
> Period E (9:45-10:45)
> 
> Period B (10:55-12:05)
> 
> Lunch (12:05-12:45)
> 
> Period A (12:45-1:55)
> 
> Period G (2:05-3:05)
> 
> Optional Tutorial (3:10-3:40)

**Comment by SheepTester** [comment]
These are the event strings we have to deal with:
```html
<p><i>&nbsp; &nbsp;Tuesday,April 10</i><br></p><p><span>Period D (8:25-9:45)</span></p><p><span>Brunch (9:45-10:00)</span></p><p><span>Period E (10:00-11:15)</span></p><p><span>Period B (11:25-12:25)</span></p><p><span>Lunch (12:25-1:05)</span></p><p><span>Period A (1:05-2:05)</span></p><p><span>Period G (2:15-3:30)</span></p><p><span>&nbsp;</span></p>
```
```html
<p><i>&nbsp; &nbsp;Wednesday,April 11</i><br></p><p><span>Period C (8:25-9:30)</span></p><p><span>Brunch (9:30-9:45)</span></p><p><span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><i><u><span>FRESHMEN</span></u></i><i><span>: to Assembly(9:45-10:45), to SELF (10:55-11:55), to FlexTime (12:05-1:05)<u></u></span></i></p><p><span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><i><u><span>SOPHOMORES</span></u></i><i>: to FlexTime(9:45-10:45), to Assembly (10:55-11:55), to FlexTime (12:05-1:05)</i></p><p><span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><i><u><span>JUNIORS: </span></u></i><i><span>to FlexTime(9:45-10:45), to FlexTime (10:55-11:55), to Assembly (12:05-1:05)<u></u></span></i></p><p><span>·<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span><i><u><span>SENIORS</span></u></i><i>: to CASTstate test (9:45-11:55), to Assembly (12:05-1:05)</i></p><p><span>Lunch (1:05-1:45)<i><u></u></i></span></p><p><span>Period F (1:45-2:45)</span></p><p><span>Staff Meeting (3:00-3:45)</span></p><p><span>&nbsp;</span></p><p><i>&nbsp; &nbsp;</i></p>
```
```html
<p><i>&nbsp; &nbsp;Thursday,April 12</i><br></p><p><span>Period D (8:25-9:30)</span></p><p><span>Brunch (9:30-9:45)</span></p><p><span>Period E (9:45-10:45)</span></p><p><span>Period B (10:55-12:05)</span></p><p><span>Lunch (12:05-12:45)</span></p><p><span>Period A (12:45-1:55)</span></p><p><span>Period G (2:05-3:05)</span></p><p><span>Optional Tutorial (3:10-3:40)</span></p><p><span>&nbsp;</span></p><p><i>&nbsp; &nbsp;</i></p>
```

**Comment by SheepTester** [comment]
here's the old UGWA alternate schedule format:
```json
"3-26":{"dayname":"Monday","day":1,"monthname":"March","month":3,"date":26,"description":"Testing for juniors, FlexTime for others","periods":[{"name":"A","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":565,"hour":9,"minute":25}},{"name":"Brunch","start":{"totalminutes":565,"hour":9,"minute":25},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Flex","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":705,"hour":11,"minute":45}},{"name":"B","start":{"totalminutes":715,"hour":11,"minute":55},"end":{"totalminutes":770,"hour":12,"minute":50}},{"name":"Lunch","start":{"totalminutes":770,"hour":12,"minute":50},"end":{"totalminutes":810,"hour":13,"minute":30}},{"name":"F","start":{"totalminutes":810,"hour":13,"minute":30},"end":{"totalminutes":865,"hour":14,"minute":25}}]}
```
i now need to parse the mess wait a sec

**Comment by Velosify** [comment]
oh gods what have they done

**Comment by Velosify** [comment]
Maybe detect for `[day], [month] [date]` and  `Period [letter]`, but then you need to detect the parentheses and somehow use that

**Comment by SheepTester** [comment]
for wednesday 9:45 to 13:05:
flex
flex
flex

**Comment by Velosify** [comment]
That's the main problem

**Comment by Velosify** [comment]
Maybe hard code it for now

**Comment by SheepTester** [comment]
i will focus on UGWA first then Ugwita

Ugwita doesn't actually have support for custom alternate schedules, so I'll have to figure out its parser

**Comment by SheepTester** [comment]
```js
/(.+) \((1?[0-9]):([0-9][0-9])-(1?[0-9]):([0-9][0-9])\)/
```

**Comment by Velosify** [comment]
yay for regex

**Comment by SheepTester** [comment]
```js
let str=`Tuesday,April 10

Period D (8:25-9:45)

Brunch (9:45-10:00)

Period E (10:00-11:15)

Period B (11:25-12:25)

Lunch (12:25-1:05)

Period A (1:05-2:05)

Period G (2:15-3:30)`,
    regex=/(.+) \((1?[0-9]):([0-9][0-9])-(1?[0-9]):([0-9][0-9])\)/g,
exec,
pds = [];
while (exec = regex.exec(str)) {
let h1=+exec[2];
let h2=+exec[4];
if (h1<5)h1+=12;
if (h2<5) h2+= 12;
pds.push({
name:exec[1],
start:{
totalminutes:h1*60+ +exec[3],
hour:h1,
minute:+exec[3]
},
end:{
totalminutes:h2*60+ +exec[5],
hour:h2,
minute:+exec[5]
}
});
}
```
wee... 😞 

it's not perfect but...
## tuesday
```json
[{"name":"Period D","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Brunch","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":600,"hour":10,"minute":0}},{"name":"Period E","start":{"totalminutes":600,"hour":10,"minute":0},"end":{"totalminutes":675,"hour":11,"minute":15}},{"name":"Period B","start":{"totalminutes":685,"hour":11,"minute":25},"end":{"totalminutes":745,"hour":12,"minute":25}},{"name":"Lunch","start":{"totalminutes":745,"hour":12,"minute":25},"end":{"totalminutes":785,"hour":13,"minute":5}},{"name":"Period A","start":{"totalminutes":785,"hour":13,"minute":5},"end":{"totalminutes":845,"hour":14,"minute":5}},{"name":"Period G","start":{"totalminutes":855,"hour":14,"minute":15},"end":{"totalminutes":930,"hour":15,"minute":30}}]
```
## thursday
```json
[{"name":"Period D","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":570,"hour":9,"minute":30}},{"name":"Brunch","start":{"totalminutes":570,"hour":9,"minute":30},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Period E","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":645,"hour":10,"minute":45}},{"name":"Period B","start":{"totalminutes":655,"hour":10,"minute":55},"end":{"totalminutes":725,"hour":12,"minute":5}},{"name":"Lunch","start":{"totalminutes":725,"hour":12,"minute":5},"end":{"totalminutes":765,"hour":12,"minute":45}},{"name":"Period A","start":{"totalminutes":765,"hour":12,"minute":45},"end":{"totalminutes":835,"hour":13,"minute":55}},{"name":"Period G","start":{"totalminutes":845,"hour":14,"minute":5},"end":{"totalminutes":905,"hour":15,"minute":5}},{"name":"Optional Tutorial","start":{"totalminutes":910,"hour":15,"minute":10},"end":{"totalminutes":940,"hour":15,"minute":40}}]
```

**Comment by SheepTester** [comment]
## wednesday
```json
[{"name":"C","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":570,"hour":9,"minute":30}},{"name":"Brunch","start":{"totalminutes":570,"hour":9,"minute":30},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Flex","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":645,"hour":10,"minute":45}},{"name":"Flex","start":{"totalminutes":655,"hour":10,"minute":55},"end":{"totalminutes":715,"hour":11,"minute":55}},{"name":"Flex","start":{"totalminutes":725,"hour":12,"minute":5},"end":{"totalminutes":785,"hour":13,"minute":5}},{"name":"Lunch","start":{"totalminutes":785,"hour":13,"minute":5},"end":{"totalminutes":825,"hour":13,"minute":45}},{"name":"F","start":{"totalminutes":825,"hour":13,"minute":45},"end":{"totalminutes":885,"hour":14,"minute":45}},{"name":"Staff Meeting","start":{"totalminutes":900,"hour":15,"minute":0},"end":{"totalminutes":945,"hour":15,"minute":45}}]
```
yay

**Comment by SheepTester** [comment]
so...

"4-10":{"dayname":"Tuesday","day":2,"monthname":"April","month":4,"date":10,"description":"Tuesday,April 10","periods":[{"name":"D","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Brunch","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":600,"hour":10,"minute":0}},{"name":"E","start":{"totalminutes":600,"hour":10,"minute":0},"end":{"totalminutes":675,"hour":11,"minute":15}},{"name":"B","start":{"totalminutes":685,"hour":11,"minute":25},"end":{"totalminutes":745,"hour":12,"minute":25}},{"name":"Lunch","start":{"totalminutes":745,"hour":12,"minute":25},"end":{"totalminutes":785,"hour":13,"minute":5}},{"name":"A","start":{"totalminutes":785,"hour":13,"minute":5},"end":{"totalminutes":845,"hour":14,"minute":5}},{"name":"G","start":{"totalminutes":855,"hour":14,"minute":15},"end":{"totalminutes":930,"hour":15,"minute":30}}]},"4-11":{"dayname":"Tuesday","day":2,"monthname":"April","month":4,"date":11,"description":"Wednesday,April 11; FRESHMEN: to Assembly(9:45-10:45), to SELF (10:55-11:55), to FlexTime (12:05-1:05); SOPHOMORES: to FlexTime(9:45-10:45), to Assembly (10:55-11:55), to FlexTime (12:05-1:05); JUNIORS: to FlexTime(9:45-10:45), to FlexTime (10:55-11:55), to Assembly (12:05-1:05); SENIORS: to CASTstate test (9:45-11:55), to Assembly (12:05-1:05)","periods":[{"name":"D","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":570,"hour":9,"minute":30}},{"name":"Brunch","start":{"totalminutes":570,"hour":9,"minute":30},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"E","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":645,"hour":10,"minute":45}},{"name":"B","start":{"totalminutes":655,"hour":10,"minute":55},"end":{"totalminutes":725,"hour":12,"minute":5}},{"name":"Lunch","start":{"totalminutes":725,"hour":12,"minute":5},"end":{"totalminutes":765,"hour":12,"minute":45}},{"name":"A","start":{"totalminutes":765,"hour":12,"minute":45},"end":{"totalminutes":835,"hour":13,"minute":55}},{"name":"G","start":{"totalminutes":845,"hour":14,"minute":5},"end":{"totalminutes":905,"hour":15,"minute":5}},{"name":"Flex","start":{"totalminutes":910,"hour":15,"minute":10},"end":{"totalminutes":940,"hour":15,"minute":40}}]},"4-12":{"dayname":"Tuesday","day":2,"monthname":"April","month":4,"date":12,"description":"Thursday,April 12; optional flex","periods":[{"name":"C","start":{"totalminutes":505,"hour":8,"minute":25},"end":{"totalminutes":570,"hour":9,"minute":30}},{"name":"Brunch","start":{"totalminutes":570,"hour":9,"minute":30},"end":{"totalminutes":585,"hour":9,"minute":45}},{"name":"Flex","start":{"totalminutes":585,"hour":9,"minute":45},"end":{"totalminutes":645,"hour":10,"minute":45}},{"name":"Flex","start":{"totalminutes":655,"hour":10,"minute":55},"end":{"totalminutes":715,"hour":11,"minute":55}},{"name":"Flex","start":{"totalminutes":725,"hour":12,"minute":5},"end":{"totalminutes":785,"hour":13,"minute":5}},{"name":"Lunch","start":{"totalminutes":785,"hour":13,"minute":5},"end":{"totalminutes":825,"hour":13,"minute":45}},{"name":"F","start":{"totalminutes":825,"hour":13,"minute":45},"end":{"totalminutes":885,"hour":14,"minute":45}},{"name":"Staff Meeting","start":{"totalminutes":900,"hour":15,"minute":0},"end":{"totalminutes":945,"hour":15,"minute":45}}]},

**Comment by SheepTester** [comment]
```html
<p>
  <i>&nbsp; &nbsp;Tuesday,April 10</i>
  <br>
</p>
<p>
  <span>Period D (8:25-9:45)</span>
</p>
<p>
  <span>Brunch (9:45-10:00)</span>
</p>
<p>
  <span>Period E (10:00-11:15)</span>
</p>
<p>
  <span>Period B (11:25-12:25)</span>
</p>
<p>
  <span>Lunch (12:25-1:05)</span>
</p>
<p>
  <span>Period A (1:05-2:05)</span>
</p>
<p>
  <span>Period G (2:15-3:30)</span>
</p>
<p>
  <span>&nbsp;</span>
</p>
```
```html
<p>
  <i>&nbsp; &nbsp;Wednesday,April 11</i>
  <br>
</p>
<p>
  <span>Period C (8:25-9:30)</span>
</p>
<p>
  <span>Brunch (9:30-9:45)</span>
</p>
<p>
  <span>·
    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
  </span>
  <i>
    <u>
      <span>FRESHMEN</span>
    </u>
  </i>
  <i>
    <span>: to Assembly(9:45-10:45), to SELF (10:55-11:55), to FlexTime (12:05-1:05)
      <u></u>
    </span>
  </i>
</p>
<p>
  <span>·
    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
  </span>
  <i>
    <u>
      <span>SOPHOMORES</span>
    </u>
  </i>
  <i>: to FlexTime(9:45-10:45), to Assembly (10:55-11:55), to FlexTime (12:05-1:05)</i>
</p>
<p>
  <span>·
    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
  </span>
  <i>
    <u>
      <span>JUNIORS: </span>
    </u>
  </i>
  <i>
    <span>to FlexTime(9:45-10:45), to FlexTime (10:55-11:55), to Assembly (12:05-1:05)
      <u></u>
    </span>
  </i>
</p>
<p>
  <span>·
    <span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span>
  </span>
  <i>
    <u>
      <span>SENIORS</span>
    </u>
  </i>
  <i>: to CASTstate test (9:45-11:55), to Assembly (12:05-1:05)</i>
</p>
<p>
  <span>Lunch (1:05-1:45)
    <i>
      <u></u>
    </i>
  </span>
</p>
<p>
  <span>Period F (1:45-2:45)</span>
</p>
<p>
  <span>Staff Meeting (3:00-3:45)</span>
</p>
<p>
  <span>&nbsp;</span>
</p>
<p>
  <i>&nbsp; &nbsp;</i>
</p>
```
```html
<p>
  <i>&nbsp; &nbsp;Thursday,April 12</i>
  <br>
</p>
<p>
  <span>Period D (8:25-9:30)</span>
</p>
<p>
  <span>Brunch (9:30-9:45)</span>
</p>
<p>
  <span>Period E (9:45-10:45)</span>
</p>
<p>
  <span>Period B (10:55-12:05)</span>
</p>
<p>
  <span>Lunch (12:05-12:45)</span>
</p>
<p>
  <span>Period A (12:45-1:55)</span>
</p>
<p>
  <span>Period G (2:05-3:05)</span>
</p>
<p>
  <span>Optional Tutorial (3:10-3:40)</span>
</p>
<p>
  <span>&nbsp;</span>
</p>
<p>
  <i>&nbsp; &nbsp;</i>
</p>
```

**Comment by SheepTester** [comment]
this isn't a problem anymore I think

I hope

maybe

perhaps

**Comment by SheepTester** [comment]
lol I like how I nonchalantly did stuff on my birthday
