### ISSUE TITLE
Add alternate schedules

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#4]
The only reason why people even use TheGunnApp is because it features alternate schedules, and the school is notorious for it.
- [x] add alternate schedule support to `/schedule` or something

It might help others who want to make their own schedule app if we included a text, JSON, and/or XML file including the alternate schedules from the [PDF they've provided](http://gunn.pausd.org/sites/default/files/ALTERNATE%20SCHEDULES%2C%202017-18.pdf).
- [x] come up with a format for an alternate schedule for JSON and TXT
- [x] put those on the repository/Github Gist

I'll probably make a JS thing that reads off a table copied and pasted from the PDF that makes the things for us.

**Comment by SheepTester** [comment]
## JSON format
### Main
```javascript
[{/* alt-schedule */},{/* alt-schedule */},/* ... */]
```
### alt-schedule
```javascript
{
  day:"Tuesday",
  month:8,
  date:15,
  description:"Extended D period,\nshorter FlexTime",
  periods:[{/* period */},{/* period */},/* ... */]
}
```
### period
```javascript
{
  name:"Period G",
  start:{/* time */},
  end:{/* time */}
}
```
### time
```javascript
{
  hour:14,
  minute:25,
  totalminutes:865
}

**Comment by SheepTester** [comment]
screw text formats

JSON is better

**Comment by SheepTester** [comment]
Screw that; the PDF they gave us can't be copied and pasted from and must be manually reformatted.

Which I did.

Screw them.

On a side note,
```javascript
  description:"Extended D period,\nshorter FlexTime",
```
I've removed the newlines from the descriptions. Yeah.

**Comment by SheepTester** [comment]
used
```javascript
var days='Sunday Monday Tuesday Wednesday Thursday Friday Saturday'.split(' '),
months='zeroIndexed?Nah January February March April May June July August September October November December'.split(' ')
function time(string) {
var hr=+string.slice(0,string.indexOf(':')),
min=+string.slice(string.indexOf(':')+1);
hr=hr<8?hr+12:hr;
return {
hour:hr,minute:min,totalminutes:hr*60+min
}
}
for (var i of stf) {
if (~i[0].indexOf('-'));
else {
var pe=[];
for (var j=3;j<i.length;j++) {
pe.push({
name:i[j].slice(0,i[j].indexOf('(')-1),
start:time(i[j].slice(i[j].lastIndexOf('(')+1,i[j].lastIndexOf('-')))
,end:time(i[j].slice(i[j].lastIndexOf('-')+1,i[j].lastIndexOf(')')))
})
}
r.push({
dayname:i[0],
day:days.indexOf(i[0]),
monthname:i[1].slice(0,i[1].indexOf(' ')),
month:months.indexOf(i[1].slice(0,i[1].indexOf(' '))),
date:+i[1].slice(i[1].indexOf(' ')+1),
description:i[2],
periods:pe
})
}
}
```
which I hastily typed in the JS console. It actually worked on the first go! Whoo!

The months and days aren't zero-indexed, as in you'd need to have a placeholder zeroth month if you wanted to use something like `months[8]` for August

**Comment by SheepTester** [comment]
No one has anything to say about this?

**Comment by PooleHenry** [comment]
Awesome!

**Comment by SheepTester** [comment]
Hurra! `/schedule/apptest.html` shows a working version of the more lightweight schedule app

One might wonder why there's no customisation or date selection, but the app can be customised with outside JavaScript (it was made to be easily put into an app)

Also, I made a colour picker thing (it's a remake of [`simplecolour.js`](https://sheeptester.github.io/javascripts/)) at `colourtest.html`

And the date picker is at `datetest.html`

For the colour and date pickers, those can be restyled. Same with the new schedule app, but I like the way it is now.

I'm happy :)
