### ISSUE TITLE
Make this a native app.

### ISSUE THREAD

**Issue by illemonati** [Orbiit/gunn-web-app#47]
I have posted this in the other issue but I think it is of the upmost importance to wrap this in something like [CORDOVA](https://cordova.apache.org/) or its extension [PHONEGAP](https://phonegap.com/) and put it on the native app stores so more people can use your awesome project.

**Comment by Velosify** [comment]
ok good luck

**Comment by SheepTester** [comment]
No thanks, PWAs for the win!
