### ISSUE TITLE
above and beyond features

### ISSUE THREAD

**Issue by PooleHenry** [Orbiit/gunn-web-app#5]
should we have features that go beyond what the original one did?

what would they be?

**Comment by SheepTester** [comment]
We can stalk the app store reviews for user suggestions, or ask the app users for some feature ideas

**Comment by SheepTester** [comment]
> select day in the future (not just today, tomorrow) using a calendar UI or smth and see its schedule
says T.S.

**Comment by SheepTester** [comment]
> show a preview of the week's schedule, including alternates

says N.M.

**Comment by SheepTester** [comment]
> club list

requests AA

**Comment by SheepTester** [comment]
All future features will be placed in UGWA 2, which I'll place in a separate thread
