### ISSUE TITLE
24 hour time

### ISSUE THREAD

**Issue by tinmarr** [Orbiit/gunn-web-app#56]
# I think that you should make an option for 24 hour time. It would be great for us Europeans.
### You could make an option under the theme selection that makes you chose 24 hour or 12 hour time.

**Comment by Velosify** [comment]
I support

**Comment by SheepTester** [comment]
will do

**Comment by SheepTester** [comment]
Added in 0d9b440082ba043bbb70ffd7f57dc9e4fd392ab4
