### ISSUE TITLE
Barcode labels

### ISSUE THREAD

**Issue by burgerhex** [Orbiit/gunn-web-app#71]
Impressive application!

I’d like to request a feature where barcodes can be labeled with a small text box so that it’s easy to keep track of multiple barcodes. The reason I’m requesting this is that I am usually the one who signs in my friends at FlexTime, so I could save all my friends’ barcodes and know which ones to scan.

**Comment by SheepTester** [comment]
I agree; will implement eventually

**Comment by SheepTester** [comment]
Added in 1b990d36ddeba812d6cd5c1e4edf738dd2a29504
