### ISSUE TITLE
don't show time in period in tab title by default?

### ISSUE THREAD

**Issue by SheepTester** [Orbiit/gunn-web-app#82]
otherwise Google will see it; instead, perhaps it would only turn it on once the user clicks something?

**Comment by SheepTester** [comment]
![image](https://user-images.githubusercontent.com/22133785/57056577-3befbd80-6c58-11e9-8102-4a816c6067ef.png)

**Comment by Velosify** [comment]
If possible just display it once the window is in focus

**Comment by SheepTester** [comment]
If Google can fetch all the schedules, I'm quite sure Google'll focus the window too. Probably not an effective counterGoogle measure
