### ISSUE TITLE
Change the schedule to the next day 30 minutes after the last event ends

### ISSUE THREAD

**Issue by anematode** [Orbiit/gunn-web-app#83]
This is a suggestion rather than an issue. It's unusual that you have to check what the schedule is for a day after the day is finished. This is usually the case if you're seeing custom events (i.e. those pulled directly from the Google Calendar) or if you were absent. Thus, I recommend that you change the default schedule -- that is, the schedule which displays when first opening UGWA -- to the following day if the current time is 30 minutes after the last event / period of the day.

**Comment by SheepTester** [comment]
good idea, will do

**Comment by SheepTester** [comment]
oh! this is UGWA! I can make this as hacky as I want, great!

**Comment by Velosify** [comment]
Perhaps the 30 minutes delay could be customizable in settings as well
That way some can delay it several hours if they wish and I can delay it by 0 seconds

**Comment by SheepTester** [comment]
> Perhaps the 30 minutes delay could be customizable in settings as well
> That way some can delay it several hours if they wish and I can delay it by 0 seconds

meh I think I'll make it immediate and I won't make a setting for it because inputs are messy
