### ISSUE TITLE
update setInterval begins at the wrong time

### ISSUE THREAD

**Issue by anematode** [Orbiit/gunn-web-app#84]
I found this when perusing through your code. This is assuming you wish the update() function to be called once per minute, and at the beginning of each minute (relative to clock time, not time of opening). That is, if you open the app at 16:00:05, it should call update initially, then call it at (or around) 16:01:00. See schedule/main.js:239-244:

```js
setTimeout(()=>{
    update();
    setInterval(()=>{
      update();
    },60000);
  },Math.floor(new Date()/1000)%60);
```

The initial setTimeout has an erroneous timeout length. First of all, the output here is in seconds, while setTimeout takes ms, so you should multiply by 1000: or more simply, don't divide by 1000 in the first place and change the 60 to 60000. Second, the floor function is unnecessary; both the modulo and setTimeout can deal with non-integers, as long as they're positive. Finally, the expression needs to be negated and added to 60. Suppose UGWA is opened at 16:00:50. Then the initial timeout (removing the /1000) is:

(new Date()) % 6e4 -> 50000 ms -> 50 s -> calls setInterval at 16:01:40.

Thus, I respectively suggest you update this section of code to read:

```js
setTimeout(()=>{
    update();
    setInterval(()=>{
      update();
    },60000);
  },Math.max(6e4-((new Date())%6e4), 1e3));
```

The Math.max is there to prevent update() from being called twice in rapid succession, in case the user opens up the program at, say, 16:00:59.5.

**Comment by SheepTester** [comment]
Alternatively, I could hook up the update timeout to the seconds counter, since it occurs more frequently, and setInterval pauses on some compoopers when they sleep. Since the code for--

Oh, and also schedule/main.js isn't used in UGWA; it's for its [predecesor](https://orbiit.github.io/gunn-web-app/schedule/)

**Comment by SheepTester** [comment]
Gunn Schedule isn't being maintained anymore, so I won't fix the bugs it has.
