### ISSUE TITLE
Incorrect schedule displays on October 10th, 2018

### ISSUE THREAD

**Issue by anematode** [Orbiit/gunn-web-app#85]
See attached image. October 10th gives a schedule of all-day Brunch, 8:30 - 12:00, but it should say "SELF" or "PSAT" or something.
![Screen Shot 2019-05-01 at 22 05 59](https://user-images.githubusercontent.com/26530804/57057843-b3c1e600-6c60-11e9-9eaf-fc0bf3dc28f2.png)

**Comment by SheepTester** [comment]
Perhaps `ALL STUDENTS ATTEND` -> flex, and I'll add a note for it somewhere so I don't accidentally revert the change without not breaking this schedule in the future
