### ISSUE TITLE
Inconsistent brunch length

### ISSUE THREAD

**Issue by acrantel** [Orbiit/gunn-web-app#92]
For some days brunch displays as 15 minutes but for other days brunch displays as 5 minutes.
example:
August 13-16: Brunch = 15 minutes
August 19-23: Brunch = 5 minutes

**Comment by SheepTester** [comment]
The [normal schedule on the Gunn website](https://gunn.pausd.org/our-school/bell-schedule) says brunch is normally 5 minutes long, but the alternate schedule events list brunch as 15 minutes long. Evidently, this is a conscious decision made by the wise and infallible Gunn administration, so one should not doubt them.
