### ISSUE TITLE
Unexpected behavior when trying to go back by a day

### ISSUE THREAD

**Issue by Wyxuan1** [Orbiit/gunn-web-app#95]
Hey Sean,
Looking at the Gunn App, when I try to click past to 'Tuesday' (August 13), I can't go back to monday nor the day before. There is no behavior, except the button animation. I can go forward and backwards by a day, but I can't do this after I go past the 'Tuesday' barrier. Switiching the UA, and using it in incog doesn't change it either.

**Comment by SheepTester** [comment]
This is intended behaviour; you aren't supposed to be able to go outside of the school year. However, I should probably indicate that better by making the buttons disabled, so I'll keep this issue open for now
