### ISSUE TITLE
Permit the export of period names, other settings as JSON to allow easy syncing of settings between devices

### ISSUE THREAD

**Issue by anematode** [Orbiit/gunn-web-app#96]
If one has two or more devices, this is extremely helpful.

Automatic synchronization of the assignments thing, in particular, would be highly utile. I would probably actually use the assignments thing if this was possible. One way to do this would to have user accounts (completely optional) to store assignments.

I can try implement this if you like; perhaps I will fork ugwa!!!

**Comment by SheepTester** [comment]
I think it'll just grab all the properties in localStorage starting with `[gunn-web-app] ` and put them in JSON format; when imported, it'll override the properties and also cache the background images if necessary

**Comment by SheepTester** [comment]
Implemented in aeb7005191a34a9576bbca71d729e1bad5ef8db6 🎉

**Comment by SheepTester** [comment]
Asssync comes later
