### ISSUE TITLE
Grade Calculator

### ISSUE THREAD

**Issue by Sordamente** [Orbiit/gunn-web-app#97]
So there could be a simple grade calculator. You have a class, which can have any number of semesters, which could have any number of buckets (with weights) which could have any number of assignments. You input your grades and it calculates your grade per class, gpa, unweighted gpa, and final grade requirements for your goals. 

To add to this, can we do something where you can input a variable as your grade and see how it would affect your grade? Like, you can say 'x' is my current grade for the final so then it'll show how 'x' could affect your grade (i.e. when x = 0%, 100%, 50% and 95%). And you could have more than one variable and call them whatever you want.

**Comment by SheepTester** [comment]
I feel like this would be better as a Schoology userscript/extension because you wouldn't have to copy over all your scores

**Comment by SheepTester** [comment]
There's a link to an epic grade calculator in UGWA now: http://www.gpac.tk
