### ISSUE TITLE
Easier creation of assignments

### ISSUE THREAD

**Issue by Sordamente** [Orbiit/gunn-web-app#98]
I use mobile primarily for UGWA, and it's a bit of a pain to create assignments right now. I suggest you do something similar to "google todo", where you can instantly create an assignment with just a description, and then if you want more detail you can press a button and set a due date, class, etc. It would make it much simpler to make assignments.

**Comment by tinmarr** [comment]
You should only do this for the mobile version...

**Comment by Sordamente** [comment]
For me, personally, the reason I like assignment tracking apps is that they just help me remember which assignments I have. I don't need extra information and I'm definitely too lazy to input due dates and stuff by hand for every assignment.

**Comment by SheepTester** [comment]
By default it should automatically fill out the rest of the assignment for you; the default due date is the day you're currently viewing, the period is set to "the day," and the category is homework.

**Comment by SheepTester** [comment]
By the way, you don't need to fill out the other details? The defaults should be sufficient for your needs.
